// <auto-generated />
using System;
using ApiRendaVariavel.Infraestruture.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiRendaVariavel.Migrations
{
    [DbContext(typeof(RendaVariavelDbContext))]
    partial class RendaVariavelDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiRendaVariavel.Domain.Entities.FundoImobiliario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID_FUNDO_IMOBILIARIO");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Cnpj")
                        .HasMaxLength(14)
                        .HasColumnType("nvarchar(14)")
                        .HasColumnName("CNPJ");

                    b.Property<int?>("CotasEmitidas")
                        .HasColumnType("int")
                        .HasColumnName("COTAS_EMITIDAS");

                    b.Property<DateTime?>("DataHoraUltimaAtualizacao")
                        .HasColumnType("datetime2")
                        .HasColumnName("DATA_HORA_ULTIMA_ATUALIZACAO");

                    b.Property<string>("Mandato")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MANDATO");

                    b.Property<int?>("NumeroDeCotistas")
                        .HasColumnType("int")
                        .HasColumnName("NUMERO_COTISTAS");

                    b.Property<string>("PrazoDeDuracao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PRAZO_DURACAO");

                    b.Property<string>("PublicoAlvo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("PUBLICO_ALVO");

                    b.Property<string>("RazaoSocial")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("RAZAO_SOCIAL");

                    b.Property<string>("Segmento")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("SEGMENTO");

                    b.Property<decimal?>("TaxaDeAdministracao")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("TAXA_ADMINISTRACAO");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)")
                        .HasColumnName("TICKER");

                    b.Property<string>("TipoDeGestao")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasColumnName("TIPO_GESTAO");

                    b.Property<decimal?>("UltimoRendimento")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("ULTIMO_RENDIMENTO");

                    b.Property<decimal?>("Vacancia")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VACANCIA");

                    b.Property<decimal?>("ValorPatrimonial")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VALOR_PATRIMONIAL");

                    b.Property<decimal?>("ValorPatrimonialPorCota")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("VALOR_PATRIMONIAL_POR_COTA");

                    b.Property<string>("tipoFundoImobiliario")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TIPO_INVESTIMENTO");

                    b.HasKey("Id");

                    b.HasIndex("Ticker")
                        .IsUnique();

                    b.ToTable("FUNDOS_IMOBILIARIOS", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
